Transform: AWS::Serverless-2016-10-31
Resources:
  MacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: s3://cf-macros-explode/93405e2e316460c632567238a67277a4
      Handler: explode.handler
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Explode
      FunctionName:
        Fn::GetAtt:
        - MacroFunction
        - Arn
