#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ -z "$1" ]; then
  echo "Provide environment type as parameter: dev / staging / prod"
  exit 0
fi

project_name="tweleve-factor-app-001"
stack_name="$project_name-$1-stack"

echo "Destroying $stack_name..."
aws cloudformation delete-stack --stack-name "$stack_name"

echo "Also remove application?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) aws cloudformation delete-stack --stack-name "$project_name-application-stack"; break;;
        No ) exit;;
    esac
done
