AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
  ApplicationName:
    Type: String
  EnvironmentType:
    Type: String
    AllowedValues:
      - "dev"
      - "staging"
      - "prod"

Mappings:
  EnvironmentMap:
    dev:
      Suffix: "dev"
      InstanceType: "t3.micro"
      MinInstances: 1
    staging:
      Suffix: "staging"
      InstanceType: "t3.small"
      MinInstances: 2
    prod:
      Suffix: "prod"
      InstanceType: "t3.small"
      MinInstances: 3

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - "aws-elasticbeanstalk-ec2-role"

  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ApplicationName
      Description: "Environment created by CloudFormation"
      EnvironmentName: !Join [ "-", [ !Ref ProjectName, !FindInMap [ EnvironmentMap, !Ref EnvironmentType, Suffix ] ] ]
      SolutionStackName: "64bit Amazon Linux 2 v3.1.4 running Corretto 8"
      OptionSettings:
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfile
        - Namespace: 'aws:autoscaling:launchconfiguration'
          OptionName: InstanceType
          Value: !FindInMap [ EnvironmentMap, !Ref EnvironmentType, InstanceType ]
        - Namespace: 'aws:autoscaling:asg'
          OptionName: MinSize
          Value: !FindInMap [ EnvironmentMap, !Ref EnvironmentType, MinInstances ]
