#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Provide environment type as parameter: dev / staging / prod"
  exit 0
fi

project_name="mk999"
stack_name="$project_name-$1-stack"
application_name="$project_name-devprodparity"

echo "Providing application if needed..."
aws cloudformation deploy \
  --stack-name "$project_name-application-stack" \
  --template-file application.yml \
  --parameter-overrides \
      ApplicationName="$application_name"

echo "Building $stack_name..."
aws cloudformation deploy \
  --stack-name "$stack_name" \
  --template-file environments.yml \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
      ProjectName="$project_name" \
      ApplicationName="$application_name" \
      EnvironmentType="$1"
